/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.67
 * Generated at: 2024-05-31 00:30:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view.sanpham;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class themsanpham_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("	<head>\n");
      out.write("		<!-- Required meta tags -->\n");
      out.write("		<meta charset=\"utf-8\" />\n");
      out.write("		<meta\n");
      out.write("			name=\"viewport\"\n");
      out.write("			content=\"width=device-width, initial-scale=1, shrink-to-fit=no\"\n");
      out.write("		/>\n");
      out.write("		<title>Booksto - Responsive Bootstrap 4 Admin Dashboard Template</title>\n");
      out.write("		<!-- Favicon -->\n");
      out.write("		<link rel=\"shortcut icon\" href=\"images/favicon.ico\" />\n");
      out.write("		<!-- Bootstrap CSS -->\n");
      out.write("		<link rel=\"stylesheet\" href=\"/Web/style/css/bootstrap.min.css\" />\n");
      out.write("		<link rel=\"stylesheet\" href=\"/Web/style/css/dataTables.bootstrap4.min.css\" />\n");
      out.write("		<!-- Typography CSS -->\n");
      out.write("		<link rel=\"stylesheet\" href=\"/Web/style/css/typography.css\" />\n");
      out.write("		<!-- Style CSS -->\n");
      out.write("		<link rel=\"stylesheet\" href=\"/Web/style/css/style.css\" />\n");
      out.write("		<!-- Responsive CSS -->\n");
      out.write("		<link rel=\"stylesheet\" href=\"/Web/style/css/responsive.css\" />\n");
      out.write("	</head>\n");
      out.write("	<body>\n");
      out.write("		<!-- loader Start -->\n");
      out.write("		<div id=\"loading\">\n");
      out.write("			<div id=\"loading-center\"></div>\n");
      out.write("		</div>\n");
      out.write("		<!-- loader END -->\n");
      out.write("		<!-- Wrapper Start -->\n");
      out.write("		<div class=\"wrapper\">\n");
      out.write("			<!-- Page Content  -->\n");
      out.write("			\n");
      out.write("			<div id=\"content-page\" class=\"content-page\">\n");
      out.write("				<div class=\"container-fluid\">\n");
      out.write("					<div class=\"row\">\n");
      out.write("						<div class=\"col-sm-12\">\n");
      out.write("							<div class=\"iq-card\">\n");
      out.write("								<div class=\"iq-card-header d-flex justify-content-between\">\n");
      out.write("									<div class=\"iq-header-title\">\n");
      out.write("										<h4 class=\"card-title\">Them sách</h4>\n");
      out.write("									</div>\n");
      out.write("								</div>\n");
      out.write("								<div class=\"iq-card-body\">\n");
      out.write("									<form action=\"../../uploadProduct\" method=\"POST\"  enctype=\"multipart/form-data\">\n");
      out.write("										<div class=\"form-group\">\n");
      out.write("											<label>Ten Sach:</label>\n");
      out.write("											<input type=\"text\" class=\"form-control\" name=\"name\"/>\n");
      out.write("										</div>\n");
      out.write("										<div class=\"form-group\">\n");
      out.write("											<label>Danh muc sach:</label>\n");
      out.write("											<select\n");
      out.write("												class=\"form-control\"\n");
      out.write("												id=\"exampleFormControlSelect1\"\n");
      out.write("											>\n");
      out.write("												<option selected=\"\" disabled=\"\">Danh muc sach</option>\n");
      out.write("												<option>General Books</option>\n");
      out.write("												<option>History Books</option>\n");
      out.write("												<option>Horror Story</option>\n");
      out.write("												<option>Arts Books</option>\n");
      out.write("												<option>Film & Photography</option>\n");
      out.write("												<option>Business & Economics</option>\n");
      out.write("												<option>Comics & Mangas</option>\n");
      out.write("												<option>Computers & Internet</option>\n");
      out.write("												<option> Sports</option>\n");
      out.write("												<option> Travel & Tourism</option>\n");
      out.write("											</select>\n");
      out.write("										</div>\n");
      out.write("										<div class=\"form-group\">\n");
      out.write("											<label>Tac Gia sách:</label>\n");
      out.write("											<select\n");
      out.write("												class=\"form-control\"\n");
      out.write("												id=\"exampleFormControlSelect2\"\n");
      out.write("												id=\"ma_loai\"\n");
      out.write("											>\n");
      out.write("												<option selected=\"\" disabled=\"\" value=\"1\">Tac gia sách</option>\n");
      out.write("												<option value=\"2\">Jhone Steben</option>\n");
      out.write("												<option value=\"3\">John Klok</option>\n");
      out.write("												<option value=\"4\">Ichae Semos</option>\n");
      out.write("												<option value=\"5\">Jules Boutin</option>\n");
      out.write("												<option value=\"6\">Kusti Franti</option>\n");
      out.write("												<option value=\"7\">David King</option>\n");
      out.write("												<option value=\"8\">Henry Jurk</option>\n");
      out.write("												<option value=\"9\">Attilio Marzi</option>\n");
      out.write("												<option value=\"10\">Argele Intili</option>\n");
      out.write("												<option value=\"11\">Attilio Marzi</option>\n");
      out.write("											</select>\n");
      out.write("										</div>\n");
      out.write("										<div class=\"form-group\">\n");
      out.write("											<label>Hinh anh:</label>\n");
      out.write("											<div class=\"custom-file\">\n");
      out.write("												<input\n");
      out.write("													name=\"photo\"\n");
      out.write("													type=\"file\"\n");
      out.write("													class=\"custom-file-input\"\n");
      out.write("													accept=\"image/png, image/jpeg\"\n");
      out.write("												/>\n");
      out.write("												<label class=\"custom-file-label\">Choose file</label>\n");
      out.write("											</div>\n");
      out.write("										</div>\n");
      out.write("										<div class=\"form-group\">\n");
      out.write("											<label>Sach pdf:</label>\n");
      out.write("											<div class=\"custom-file\">\n");
      out.write("												<input\n");
      out.write("													type=\"file\"\n");
      out.write("													class=\"custom-file-input\"\n");
      out.write("													accept=\"application/pdf, application/vnd.ms-excel\"\n");
      out.write("												/>\n");
      out.write("												<label class=\"custom-file-label\">Chon file</label>\n");
      out.write("											</div>\n");
      out.write("										</div>\n");
      out.write("										<div class=\"form-group\">\n");
      out.write("											<label>Gia Sach:</label>\n");
      out.write("											<input type=\"text\" class=\"form-control\" name=\"gia\"/>\n");
      out.write("										</div>\n");
      out.write("										<div class=\"form-group\">\n");
      out.write("											<label>Noi dung:</label>\n");
      out.write("											<textarea class=\"form-control\" rows=\"4\" name=\"mota\"></textarea>\n");
      out.write("										</div>\n");
      out.write("										<button type=\"submit\" class=\"btn btn-primary\">\n");
      out.write("											Submit\n");
      out.write("										</button>\n");
      out.write("										<a href=\"../../adminKho\"  class=\"btn btn-danger\">Cancel</a>\n");
      out.write("									</form>\n");
      out.write("								</div>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("		<!-- Wrapper END -->\n");
      out.write("		<!-- Footer -->\n");
      out.write("		<footer class=\"iq-footer\">\n");
      out.write("			<div class=\"container-fluid\">\n");
      out.write("				<div class=\"row\">\n");
      out.write("					<div class=\"col-lg-6\">\n");
      out.write("						<ul class=\"list-inline mb-0\">\n");
      out.write("							<li class=\"list-inline-item\">\n");
      out.write("								<a href=\"privacy-policy.html\">Privacy Policy</a>\n");
      out.write("							</li>\n");
      out.write("							<li class=\"list-inline-item\">\n");
      out.write("								<a href=\"terms-of-service.html\">Terms of Use</a>\n");
      out.write("							</li>\n");
      out.write("						</ul>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</footer>\n");
      out.write("		<!-- Footer END -->\n");
      out.write("		<!-- color-customizer -->\n");
      out.write("\n");
      out.write("		<!-- color-customizer END -->\n");
      out.write("		<!-- Optional JavaScript -->\n");
      out.write("		<!-- jQuery first, then Popper.js, then Bootstrap JS -->\n");
      out.write("		<script src=\"/Web/style/js/jquery.min.js\"></script>\n");
      out.write("		<script src=\"/Web/style/js/popper.min.js\"></script>\n");
      out.write("		<script src=\"/Web/style/js/bootstrap.min.js\"></script>\n");
      out.write("		<script src=\"/Web/style/js/jquery.dataTables.min.js\"></script>\n");
      out.write("		<script src=\"/Web/style/js/dataTables.bootstrap4.min.js\"></script>\n");
      out.write("		<!-- Appear JavaScript -->\n");
      out.write("		<script src=\"/Web/style/js/jquery.appear.js\"></script>\n");
      out.write("		<!-- Countdown JavaScript -->\n");
      out.write("		<script src=\"/Web/style/js/countdown.min.js\"></script>\n");
      out.write("		<!-- Counterup JavaScript -->\n");
      out.write("		<script src=\"/Web/style/js/waypoints.min.js\"></script>\n");
      out.write("		<script src=\"/Web/style/js/jquery.counterup.min.js\"></script>\n");
      out.write("		<!-- Wow JavaScript -->\n");
      out.write("		<script src=\"/Web/style/js/wow.min.js\"></script>\n");
      out.write("		<!-- Apexcharts JavaScript -->\n");
      out.write("		<script src=\"/Web/style/js/apexcharts.js\"></script>\n");
      out.write("		<!-- Slick JavaScript -->\n");
      out.write("		<script src=\"/Web/style/js/slick.min.js\"></script>\n");
      out.write("		<!-- Select2 JavaScript -->\n");
      out.write("		<script src=\"/Web/style/js/select2.min.js\"></script>\n");
      out.write("		<!-- Owl Carousel JavaScript -->\n");
      out.write("		<script src=\"/Web/style/js/owl.carousel.min.js\"></script>\n");
      out.write("		<!-- Magnific Popup JavaScript -->\n");
      out.write("		<script src=\"/Web/style/js/jquery.magnific-popup.min.js\"></script>\n");
      out.write("		<!-- Smooth Scrollbar JavaScript -->\n");
      out.write("		<script src=\"/Web/style/js/smooth-scrollbar.js\"></script>\n");
      out.write("		<!-- lottie JavaScript -->\n");
      out.write("		<script src=\"/Web/style/js/lottie.js\"></script>\n");
      out.write("		<!-- am core JavaScript -->\n");
      out.write("		<script src=\"/Web/style/js/core.js\"></script>\n");
      out.write("		<!-- am charts JavaScript -->\n");
      out.write("		<script src=\"/Web/style/js/charts.js\"></script>\n");
      out.write("		<!-- am animated JavaScript -->\n");
      out.write("		<script src=\"/Web/style/js/animated.js\"></script>\n");
      out.write("		<!-- am kelly JavaScript -->\n");
      out.write("		<script src=\"/Web/style/js/kelly.js\"></script>\n");
      out.write("		<!-- am maps JavaScript -->\n");
      out.write("		<script src=\"/Web/style/js/maps.js\"></script>\n");
      out.write("		<!-- am worldLow JavaScript -->\n");
      out.write("		<script src=\"/Web/style/js/worldLow.js\"></script>\n");
      out.write("		<!-- Raphael-min JavaScript -->\n");
      out.write("		<script src=\"/Web/style/js/raphael-min.js\"></script>\n");
      out.write("		<!-- Morris JavaScript -->\n");
      out.write("		<script src=\"/Web/style/js/morris.js\"></script>\n");
      out.write("		<!-- Morris min JavaScript -->\n");
      out.write("		<script src=\"/Web/style/js/morris.min.js\"></script>\n");
      out.write("		<!-- Flatpicker Js -->\n");
      out.write("		<script src=\"/Web/style/js/flatpickr.js\"></script>\n");
      out.write("		<!-- Style Customizer -->\n");
      out.write("		<script src=\"/Web/style/js/style-customizer.js\"></script>\n");
      out.write("		<!-- Chart Custom JavaScript -->\n");
      out.write("		<script src=\"/Web/style/js/chart-custom.js\"></script>\n");
      out.write("		<!-- Custom JavaScript -->\n");
      out.write("		<script src=\"/Web/style/js/custom.js\"></script>\n");
      out.write("	</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
