/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.67
 * Generated at: 2024-05-30 08:35:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view.dangnhap;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import model.User;

public final class dangky_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("model.User");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("	<head>\n");
      out.write("		<meta charset=\"utf-8\" />\n");
      out.write("		<meta\n");
      out.write("			name=\"viewport\"\n");
      out.write("			content=\"width=device-width, initial-scale=1, shrink-to-fit=no\"\n");
      out.write("		/>\n");
      out.write("		<title>Booksto - Responsive Bootstrap 4 Admin Dashboard Template</title>\n");
      out.write("		<link rel=\"shortcut icon\" href=\"/Web/style/images/favicon.ico\" />\n");
      out.write("		<!-- Bootstrap CSS -->\n");
      out.write("		<link rel=\"stylesheet\" href=\"/Web/style/css/bootstrap.min.css\" />\n");
      out.write("		<!-- Typography CSS -->\n");
      out.write("		<link rel=\"stylesheet\" href=\"/Web/style/ss/typography.css\" />\n");
      out.write("		<!-- Style CSS -->\n");
      out.write("		<link rel=\"stylesheet\" href=\"/Web/style/css/style.css\" />\n");
      out.write("		<!-- Responsive CSS -->\n");
      out.write("		<link rel=\"stylesheet\" href=\"/Web/style/css/responsive.css\" />\n");
      out.write("	</head>\n");
      out.write("	<body>\n");
      out.write("		<!-- Sign in Start -->\n");
      out.write("		<section class=\"sign-in-page\">\n");
      out.write("			<div class=\"container p-0\">\n");
      out.write("				<div class=\"row no-gutters height-self-center\">\n");
      out.write("					<div class=\"col-sm-12 align-self-center page-content rounded\">\n");
      out.write("						<div class=\"row m-0\">\n");
      out.write("							<div class=\"col-sm-12 sign-in-page-data\">\n");
      out.write("								<div class=\"sign-in-from bg-primary rounded\">\n");
      out.write("									<h3 class=\"mb-0 text-center text-white\">Sign in</h3>\n");
      out.write("									<p class=\"text-center text-white\">\n");
      out.write("										Enter your email address and password to access admin panel.\n");
      out.write("									</p>\n");
      out.write("									<form class=\"mt-4 form-text\">\n");
      out.write("										<div class=\"form-group\">\n");
      out.write("											<label for=\"exampleInputEmail1\">Email address</label>\n");
      out.write("											<input\n");
      out.write("												type=\"email\"\n");
      out.write("												class=\"form-control mb-0\"\n");
      out.write("												id=\"exampleInputEmail1\"\n");
      out.write("												placeholder=\"Enter email\"\n");
      out.write("											/>\n");
      out.write("										</div>\n");
      out.write("										<div class=\"form-group\">\n");
      out.write("											<label for=\"exampleInputPassword1\">Password</label>\n");
      out.write("											<a href=\"#\" class=\"float-right text-dark\"\n");
      out.write("												>Forgot password?</a\n");
      out.write("											>\n");
      out.write("											<input\n");
      out.write("												type=\"password\"\n");
      out.write("												class=\"form-control mb-0\"\n");
      out.write("												id=\"exampleInputPassword1\"\n");
      out.write("												placeholder=\"Password\"\n");
      out.write("											/>\n");
      out.write("										</div>\n");
      out.write("										<div class=\"d-inline-block w-100\">\n");
      out.write("											<div\n");
      out.write("												class=\"custom-control custom-checkbox d-inline-block mt-2 pt-1\"\n");
      out.write("											>\n");
      out.write("												<input\n");
      out.write("													type=\"checkbox\"\n");
      out.write("													class=\"custom-control-input\"\n");
      out.write("													id=\"customCheck1\"\n");
      out.write("												/>\n");
      out.write("												<label class=\"custom-control-label\" for=\"customCheck1\"\n");
      out.write("													>Remember Me</label\n");
      out.write("												>\n");
      out.write("											</div>\n");
      out.write("										</div>\n");
      out.write("										<div class=\"sign-info text-center\">\n");
      out.write("											<button\n");
      out.write("												type=\"submit\"\n");
      out.write("												class=\"btn btn-white d-block w-100 mb-2\"\n");
      out.write("											>\n");
      out.write("												Sign in\n");
      out.write("											</button>\n");
      out.write("											<span\n");
      out.write("												class=\"text-dark dark-color d-inline-block line-height-2\"\n");
      out.write("												>Don't have an account?\n");
      out.write("												<a href=\"sign-up.html\" class=\"text-white\"\n");
      out.write("													>Sign up</a\n");
      out.write("												></span\n");
      out.write("											>\n");
      out.write("										</div>\n");
      out.write("									</form>\n");
      out.write("								</div>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</section>\n");
      out.write("\n");
      out.write("		<script src=\"/Web/style/js/jquery.min.js\"></script>\n");
      out.write("		<script src=\"/Web/style/js/popper.min.js\"></script>\n");
      out.write("		<script src=\"/Web/style/js/bootstrap.min.js\"></script>\n");
      out.write("		<!-- Appear JavaScript -->\n");
      out.write("		<script src=\"/Web/style/js/jquery.appear.js\"></script>\n");
      out.write("		<!-- Countdown JavaScript -->\n");
      out.write("		<script src=\"/Web/style/js/countdown.min.js\"></script>\n");
      out.write("		<!-- Counterup JavaScript -->\n");
      out.write("		<script src=\"/Web/style/js/waypoints.min.js\"></script>\n");
      out.write("		<script src=\"/Web/style/js/jquery.counterup.min.js\"></script>\n");
      out.write("		<!-- Wow JavaScript -->\n");
      out.write("		<script src=\"/Web/style/js/wow.min.js\"></script>\n");
      out.write("		<!-- Apexcharts JavaScript -->\n");
      out.write("		<script src=\"/Web/style/js/apexcharts.js\"></script>\n");
      out.write("		<!-- lottie JavaScript -->\n");
      out.write("		<script src=\"/Web/style/js/lottie.js\"></script>\n");
      out.write("		<!-- Slick JavaScript -->\n");
      out.write("		<script src=\"/Web/style/js/slick.min.js\"></script>\n");
      out.write("		<!-- Select2 JavaScript -->\n");
      out.write("		<script src=\"/Web/style/js/select2.min.js\"></script>\n");
      out.write("		<!-- Owl Carousel JavaScript -->\n");
      out.write("		<script src=\"/Web/style/js/owl.carousel.min.js\"></script>\n");
      out.write("		<!-- Magnific Popup JavaScript -->\n");
      out.write("		<script src=\"/Web/style/js/jquery.magnific-popup.min.js\"></script>\n");
      out.write("		<!-- Smooth Scrollbar JavaScript -->\n");
      out.write("		<script src=\"/Web/style/js/smooth-scrollbar.js\"></script>\n");
      out.write("		<!-- Style Customizer -->\n");
      out.write("		<script src=\"/Web/style/js/style-customizer.js\"></script>\n");
      out.write("		<!-- Chart Custom JavaScript -->\n");
      out.write("		<script src=\"/Web/style/js/chart-custom.js\"></script>\n");
      out.write("		<!-- Custom JavaScript -->\n");
      out.write("		<script src=\"/Web/style/js/custom.js\"></script>\n");
      out.write("	</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
